package com.roche.multithreading;

import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;

/**
 * 
 * Class for setting a name that prepends all threads created by this factory
 * 
 */
public class NamePrependingThreadFactory implements ThreadFactory {

	private ThreadFactory defaultThreadFactory;
	private String namePrepender;

	/**
	 * 
	 * @param namePrepender
	 *            name that prepends all thread names generated by this factory
	 */
	public NamePrependingThreadFactory(String namePrepender) {
		super();
		defaultThreadFactory = Executors.defaultThreadFactory();
		this.namePrepender = namePrepender;
	}

	@Override
	public Thread newThread(Runnable r) {
		Thread newThread = defaultThreadFactory.newThread(r);
		newThread.setName(namePrepender + newThread.getName());
		return newThread;
	}

}
