package com.roche.sequencing.bioinformatics.common.fastqtool.settings;

public enum MultipleMatchesActionEnum {
	PUT_ENTIES_WITH_MULTIPLE_MATCHES_IN_SINGLE_MATCHES_FILE, PUT_ENTRIES_WITH_MULTIPLE_MATCHES_IN_OWN_FILE, PUT_ENTRIES_WITH_MULTIPLE_MATCHES_IN_NOT_FOUND_FILE, EXCLUDE_ENTRIES_WITH_MULTIPLE_MATCHES;

}
